// Generated by CoffeeScript 1.6.1
(function() {

  describe("RequireJS namespacing", function() {
    beforeEach(function() {
      return jasmine.addMatchers({
        requirejsTobeUndefined: function() {
          return {
            compare: function() {
              return {
                pass: typeof requirejs === "undefined"
              };
            }
          };
        },
        requireTobeUndefined: function() {
          return {
            compare: function() {
              return {
                pass: typeof require === "undefined"
              };
            }
          };
        },
        defineTobeUndefined: function() {
          return {
            compare: function() {
              return {
                pass: typeof define === "undefined"
              };
            }
          };
        }
      });
    });
    it("check that the RequireJS object is present in the global namespace", function() {
      expect(RequireJS).toEqual(jasmine.any(Object));
      return expect(window.RequireJS).toEqual(jasmine.any(Object));
    });
    return it("check that requirejs(), require(), and define() are not in the global namespace", function() {
      expect({}).requirejsTobeUndefined();
      expect({}).requireTobeUndefined();
      expect({}).defineTobeUndefined();
      expect(window.requirejs).not.toBeDefined();
      expect(window.require).not.toBeDefined();
      return expect(window.define).not.toBeDefined();
    });
  });

  describe("RequireJS module creation", function() {
    var inDefineCallback, inRequireCallback;
    inDefineCallback = void 0;
    inRequireCallback = void 0;
    return it("check that we can use RequireJS to define() and require() a module", function(done) {
      var d1, d2, func;
      d1 = $.Deferred();
      d2 = $.Deferred();
      func = function() {
        inDefineCallback = false;
        inRequireCallback = false;
        RequireJS.define("test_module", [], function() {
          inDefineCallback = true;
          d1.resolve();
          return {
            module_status: "OK"
          };
        });
        return RequireJS.require(["test_module"], function(test_module) {
          inRequireCallback = true;
          expect(test_module.module_status).toBe("OK");
          return d2.resolve();
        });
      };
      func();
      return $.when(d1, d2).done(function() {
        expect(inDefineCallback).toBeTruthy();
        return expect(inRequireCallback).toBeTruthy();
      }).always(done);
    });
  });

}).call(this);
