%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_TimeService
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_master-opu_o.2015-06-23_20/otp_src_18/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_TIMESERVICE_HRL).
-define(COSTIME_TIMESERVICE_HRL, true).




-endif.


